export const allCurrenciesResults = [
  {
    id: 'ZEC-BTC',
    base_currency: 'ZEC',
    quote_currency: 'BTC',
    base_min_size: '0.01000000',
    base_max_size: '1500.00000000',
    quote_increment: '0.00000100',
    base_increment: '0.00010000',
    display_name: 'ZEC/BTC',
    min_market_funds: '0.001',
    max_market_funds: '30',
    margin_enabled: false,
    post_only: false,
    limit_only: true,
    cancel_only: false,
    status: 'online',
    status_message: ''
  },
  {
    id: 'EOS-USD',
    base_currency: 'EOS',
    quote_currency: 'USD',
    base_min_size: '0.10000000',
    base_max_size: '5000.00000000',
    quote_increment: '0.00100000',
    base_increment: '0.10000000',
    display_name: 'EOS/USD',
    min_market_funds: '10',
    max_market_funds: '100000',
    margin_enabled: false,
    post_only: false,
    limit_only: false,
    cancel_only: false,
    status: 'online',
    status_message: ''
  },
  {
    id: 'BTC-EUR',
    base_currency: 'BTC',
    quote_currency: 'EUR',
    base_min_size: '0.00100000',
    base_max_size: '200.00000000',
    quote_increment: '0.01000000',
    base_increment: '0.00000001',
    display_name: 'BTC/EUR',
    min_market_funds: '10',
    max_market_funds: '600000',
    margin_enabled: false,
    post_only: false,
    limit_only: false,
    cancel_only: false,
    status: 'online',
    status_message: ''
  }
];
